### ISSUE TITLE
migration towards mlpack ?

### ISSUE THREAD

**Issue by jbferet** [allanvc/emstreeR#2]
thank you for this very useful package. 
I recently encountered a problem with the continuous integration of one of my packages, as emstreeR and RcppMLPACK are not distributed on the CRAN anymore. 
Are you considering using the R package mlpack instead of RcppMLPACK in a next version ? This would allow me to use emstreeR again.
Thank you!
best regards, 
jb

**Comment by allanvc** [comment]
Hello jb,

I apologize for my delay in replying to you.
I am sorry about the discontinuation of emstreer and RcppMLPACK. I was
caught by surprise too and tried to contact the RcppMLPACK creator to find
a quick way of maintaining the package, but had no success.
I do intend to shift the dependency to mlpack, but I am currently very busy
with other projects. Unfortunately, I can't provide you with a date and
can’t guarantee it will be done before May, but I will try to.
I will keep you posted!
Thanks,
Allan

**Comment by allanvc** [comment]
Thanks to @nacnudus, {emstreeR} now uses {mlpack} and is on its way to CRAN.
Thanks,
Allan

**Comment by jbferet** [comment]
Thank you Allan for the update! that's great news. 
I was kept busy these past weeks but i will check that now that I have a bit more time. 
Cheers, 
jb
